// ─────────────────────────────────────────────────────────────────────────────
// Brain geometry utilities — positions come from OBJ surface sampling
// (public/brain-surface.bin, generated by scripts/sampleBrain.mjs).
//
// Coordinate system after OBJ transform (see sampleBrain.mjs):
//   X  frontal/anterior (−)  →  occipital/posterior (+)   range ≈ [-1.15, +1.15]
//   Y  inferior (−)          →  superior (+)               range ≈ [-0.97, +0.97]
//   Z  left hemisphere (−)   →  right hemisphere (+)       range ≈ [-0.94, +0.94]
// ─────────────────────────────────────────────────────────────────────────────

// ─── Region colors (6 lobes) ──────────────────────────────────────────────────

// Pure, fully-saturated hues — additive blending on black makes these vivid.
// Max component at 1.0, minimal contamination from other channels.
export const LOBE_COLORS: Array<[number, number, number]> = [
  [0.05, 1.00, 0.45],  // 0 frontal    — electric green
  [0.70, 0.20, 1.00],  // 1 parietal   — saturated violet
  [0.00, 0.90, 1.00],  // 2 temporal   — pure cyan
  [1.00, 0.55, 0.05],  // 3 occipital  — vivid orange
  [0.80, 0.92, 1.00],  // 4 cerebellum — cool bright white
  [1.00, 0.05, 0.60],  // 5 brainstem  — hot magenta
]

/**
 * Classify a surface point into one of the 6 navigation regions.
 *
 * Coordinate space (post-transform, camera at z = +4):
 *   X: frontal/anterior (−1.15) → occipital/posterior (+1.15)  →  screen LEFT to RIGHT
 *   Y: inferior (−0.97) → superior (+0.97)                      →  screen BOTTOM to TOP
 *   Z: left hemisphere (−0.94) → right hemisphere (+0.94)       →  depth (z+ faces camera)
 *
 * Strategy: pure X,Y boundaries (no Z component).
 * Particles at the same screen (X,Y) always share a lobe regardless of Z depth.
 * This eliminates the depth-mixing artifact that made regions look like a cloud.
 *
 * Layout (as seen from camera at z=+4):
 *
 *   ┌─────────────────────┬─────────────────────┐
 *   │ GREEN / Research    │ VIOLET / Projects   │  y > 0.32
 *   ├─────────────────────┼─────────────────────┤
 *   │ CYAN  / Skills      │ ORANGE / Hackathons │  −0.10 < y < 0.32
 *   ├─────────────────────┼─────────────────────┤
 *   │ PINK  / Obsessions  │ WHITE  / About      │  y < −0.10
 *   └─────────────────────┴─────────────────────┘
 *         x < col split        x ≥ col split
 *
 * Measured distribution (per-band x splits):
 *   F/green:18.4%  Pa/violet:19.5%  T/cyan:13.6%  O/orange:13.1%
 *   Ce/white:17.6%  Br/pink:17.8%   maxDev from 16.67%: 3.5%
 *
 * The middle band is geometrically smaller (brain is widest at top),
 * but visually spans a clear distinct horizontal strip.
 */
// Low-frequency spatial noise for organic boundary shaping.
// Three overlapping sine waves at different scales produce smooth, biologically
// plausible curves — not speckles, not straight lines.
// Returns a value in [−1, 1].
function boundaryNoise(a: number, b: number, seed: number): number {
  return (
    Math.sin(a * 3.1 + b * 2.7 + seed * 1.4) * 0.45 +
    Math.sin(a * 1.6 + b * 4.3 + seed * 2.9) * 0.35 +
    Math.sin(a * 5.2 + b * 1.8 + seed * 0.7) * 0.20
  )
}

// How far each threshold shifts (in brain-local units, range ~[−1.15, +1.15]).
// ±0.12 produces clearly visible organic curves without destabilising region sizes.
const JITTER = 0.12

export function assignLobeId(x: number, y: number, z: number): number {
  // Y-boundaries vary across the x–z surface → wavy horizontal seams.
  const yBot = -0.10 + boundaryNoise(x, z, 0) * JITTER  // organic bottom/middle split
  const yTop =  0.32 + boundaryNoise(x, z, 1) * JITTER  // organic middle/top split

  if (y < yBot) {
    // Bottom band — pink(5)=left / white(4)=right with organic vertical seam.
    const xSplit = 0.10 + boundaryNoise(y, z, 2) * JITTER
    return x < xSplit ? 5 : 4
  }
  if (y > yTop) {
    // Top band — green(0)=left / violet(1)=right with organic vertical seam.
    const xSplit = 0.00 + boundaryNoise(y, z, 3) * JITTER
    return x < xSplit ? 0 : 1
  }
  // Middle band — cyan(2)=left / orange(3)=right with organic vertical seam.
  const xSplit = 0.06 + boundaryNoise(y, z, 4) * JITTER
  return x < xSplit ? 2 : 3
}


// ─── Chaos positions (assembly animation start) ───────────────────────────────

export function generateChaosPositions(count: number): Float32Array {
  const out = new Float32Array(count * 3)
  for (let i = 0; i < count; i++) {
    const u = Math.random(), v = Math.random()
    const theta = 2 * Math.PI * u
    const phi   = Math.acos(2 * v - 1)
    const r     = 4.5 * Math.cbrt(Math.random())
    out[i * 3]     = r * Math.sin(phi) * Math.cos(theta)
    out[i * 3 + 1] = r * Math.cos(phi)
    out[i * 3 + 2] = r * Math.sin(phi) * Math.sin(theta)
  }
  return out
}

// ─── Per-node attributes ──────────────────────────────────────────────────────

export function generateParticleSizes(count: number): Float32Array {
  const out = new Float32Array(count)
  for (let i = 0; i < count; i++) {
    out[i] = 0.060 + Math.random() * 0.036  // ~15% larger to fill gaps
  }
  return out
}

export function generatePulseOffsets(count: number): Float32Array {
  const out = new Float32Array(count)
  for (let i = 0; i < count; i++) out[i] = Math.random() * Math.PI * 2
  return out
}

// ─── Spatial grid for connection generation ───────────────────────────────────

const GRID_OFFSET = 48  // enough for coords in [-1.5, 1.5] with cell size 0.25

function gridKey(cx: number, cy: number, cz: number): number {
  return ((cx + GRID_OFFSET) & 0x7f) |
         (((cy + GRID_OFFSET) & 0x7f) << 7) |
         (((cz + GRID_OFFSET) & 0x7f) << 14)
}

function buildGrid(
  positions: Float32Array,
  count: number,
  invCell: number,
): Map<number, number[]> {
  const grid = new Map<number, number[]>()
  for (let i = 0; i < count; i++) {
    const key = gridKey(
      Math.floor(positions[i * 3]     * invCell),
      Math.floor(positions[i * 3 + 1] * invCell),
      Math.floor(positions[i * 3 + 2] * invCell),
    )
    let cell = grid.get(key)
    if (!cell) { cell = []; grid.set(key, cell) }
    cell.push(i)
  }
  return grid
}

// ─── Connection generation ────────────────────────────────────────────────────

const CONNECT_RADIUS    = 0.17
const MAX_CONN_PER_NODE = 2

export function generateNeuralConnections(
  positions: Float32Array,
  colors:    Float32Array,
  lobeIds:   Uint8Array,
  count:     number,
): { linePositions: Float32Array; lineColors: Float32Array; lineBright: Float32Array } {
  const invCell  = 1 / CONNECT_RADIUS
  const grid     = buildGrid(positions, count, invCell)
  const connCnt  = new Uint8Array(count)

  const posArr:    number[] = []
  const colArr:    number[] = []
  const brightArr: number[] = []

  function addSeg(
    i: number, j: number,
    bright: number,
    overrideCol?: [number, number, number],
  ) {
    posArr.push(
      positions[i*3], positions[i*3+1], positions[i*3+2],
      positions[j*3], positions[j*3+1], positions[j*3+2],
    )
    const col = overrideCol ?? [
      (colors[i*3]   + colors[j*3])   * 0.5,
      (colors[i*3+1] + colors[j*3+1]) * 0.5,
      (colors[i*3+2] + colors[j*3+2]) * 0.5,
    ] as [number, number, number]
    colArr.push(col[0], col[1], col[2], col[0], col[1], col[2])
    brightArr.push(bright, bright)
  }

  // ── Local cortical mesh connections ──────────────────────────────────────────
  for (let i = 0; i < count; i++) {
    if (connCnt[i] >= MAX_CONN_PER_NODE) continue

    const xi  = positions[i*3], yi = positions[i*3+1], zi = positions[i*3+2]
    const cxi = Math.floor(xi * invCell)
    const cyi = Math.floor(yi * invCell)
    const czi = Math.floor(zi * invCell)

    for (let dx = -1; dx <= 1 && connCnt[i] < MAX_CONN_PER_NODE; dx++) {
      for (let dy = -1; dy <= 1 && connCnt[i] < MAX_CONN_PER_NODE; dy++) {
        for (let dz = -1; dz <= 1 && connCnt[i] < MAX_CONN_PER_NODE; dz++) {
          const cell = grid.get(gridKey(cxi+dx, cyi+dy, czi+dz))
          if (!cell) continue

          for (const j of cell) {
            if (j <= i) continue
            if (connCnt[j] >= MAX_CONN_PER_NODE) continue

            const ddx = positions[j*3] - xi
            const ddy = positions[j*3+1] - yi
            const ddz = positions[j*3+2] - zi
            const d2  = ddx*ddx + ddy*ddy + ddz*ddz
            if (d2 > CONNECT_RADIUS * CONNECT_RADIUS || d2 < 0.0009) continue

            // Cross-region connections are skipped: their blended-color lines
            // contaminate neighboring regions visually via additive blending.
            if (lobeIds[i] !== lobeIds[j]) continue
            addSeg(i, j, 0.026)
            connCnt[i]++
            connCnt[j]++
            if (connCnt[i] >= MAX_CONN_PER_NODE) break
          }
        }
      }
    }
  }

  return {
    linePositions: new Float32Array(posArr),
    lineColors:    new Float32Array(colArr),
    lineBright:    new Float32Array(brightArr),
  }
}
